---
description: >
  Default executor for deployment jobs
docker:
  - image: 'cimg/python:<<parameters.tag>>'
working_directory: ~/app
resource_class: <<parameters.resource_class>>
parameters:
  resource_class:
    default: medium
    type: string
  tag:
    default: "3.9"
    type: string
